--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
--local Node=cc.Node:create()
--Node:setName("Node")

--Create backimage
local backimage = ccui.ImageView:create()
backimage:ignoreContentAdaptWithSize(false)
backimage:loadTexture("game/game_layer/common/ready_bg-i6p.png",0)
backimage:setTouchEnabled(true);
backimage:setLayoutComponentEnabled(true)
backimage:setName("backimage")
backimage:setTag(186)
backimage:setCascadeColorEnabled(true)
backimage:setCascadeOpacityEnabled(true)
backimage:setAnchorPoint(0.0000, 1.0000)
backimage:setPosition(0.0000, 0.0000)
if callBackProvider~=nil then
      backimage:addTouchEventListener(callBackProvider("adddesknode.lua", backimage, "OnBackTouch"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(backimage)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(300.0000, 170.0000))
layout:setLeftMargin(0.0000)
layout:setRightMargin(-300.0000)
layout:setTopMargin(0.0000)
layout:setBottomMargin(-170.0000)
Node=backimage
--Node:addChild(backimage)

--Create addbutton
local addbutton = ccui.Button:create()
addbutton:ignoreContentAdaptWithSize(false)
addbutton:loadTextureNormal("game/game_layer/common/addfriend_pressed-i6p.png",0)
addbutton:loadTexturePressed("game/game_layer/common/addfriend_disable-i6p.png",0)
addbutton:loadTextureDisabled("game/game_layer/common/addfriend_disable-i6p.png",0)
addbutton:setTitleFontSize(14)
addbutton:setTitleColor(cc.c3b(65, 65, 70))
addbutton:setScale9Enabled(true)
addbutton:setCapInsets(cc.rect(15,11,125,133))
addbutton:setLayoutComponentEnabled(true)
addbutton:setName("addbutton")
addbutton:setTag(451)
addbutton:setCascadeColorEnabled(true)
addbutton:setCascadeOpacityEnabled(true)
addbutton:setPosition(147.9812, 85.9691)
if callBackProvider~=nil then
      addbutton:addClickEventListener(callBackProvider("adddesknode.lua", addbutton, "OnAddButton"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(addbutton)
layout:setPositionPercentX(0.4933)
layout:setPositionPercentY(0.5057)
layout:setPercentWidth(0.5167)
layout:setPercentHeight(0.9118)
layout:setSize(cc.size(155.0000, 155.0000))
layout:setLeftMargin(70.4812)
layout:setRightMargin(74.5188)
layout:setTopMargin(6.5309)
layout:setBottomMargin(8.4691)
backimage:addChild(addbutton)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

