--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create backimage
local backimage = ccui.ImageView:create()
backimage:ignoreContentAdaptWithSize(false)
backimage:loadTexture("game/game_layer/common/btn_blank-i6p.png",0)
backimage:setScale9Enabled(true)
backimage:setCapInsets(cc.rect(75,40,79,44))
backimage:setTouchEnabled(true);
backimage:setLayoutComponentEnabled(true)
backimage:setName("backimage")
backimage:setTag(348)
backimage:setCascadeColorEnabled(true)
backimage:setCascadeOpacityEnabled(true)
backimage:setPosition(-7.7893, -2.3102)
backimage:setScaleX(10.0000)
backimage:setScaleY(10.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(backimage)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(2000.0000, 2000.0000))
layout:setLeftMargin(-1007.7890)
layout:setRightMargin(-992.2107)
layout:setTopMargin(-997.6898)
layout:setBottomMargin(-1002.3100)
Node:addChild(backimage)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("game/game_layer/common/shoptipsbg.png",0)
Image_1:setScale9Enabled(true)
Image_1:setCapInsets(cc.rect(178,56,167,52))
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(343)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(0.0000, 0.0000)
Image_1:setColor(cc.c3b(221, 234, 221))
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(1200.0000, 1000.0000))
layout:setLeftMargin(-600.0000)
layout:setRightMargin(-600.0000)
layout:setTopMargin(-500.0000)
layout:setBottomMargin(-500.0000)
Node:addChild(Image_1)

--Create scrollview
local scrollview = ccui.ScrollView:create()
scrollview:setBounceEnabled(true)
scrollview:setInnerContainerSize(cc.size(1200,1000))
scrollview:ignoreContentAdaptWithSize(false)
scrollview:setClippingEnabled(true)
scrollview:setBackGroundColorOpacity(102)
scrollview:setLayoutComponentEnabled(true)
scrollview:setName("scrollview")
scrollview:setTag(21)
scrollview:setCascadeColorEnabled(true)
scrollview:setCascadeOpacityEnabled(true)
scrollview:setAnchorPoint(0.0000, 1.0000)
scrollview:setPosition(0.0000, 1000.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(scrollview)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(1.0000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize(cc.size(1200.0000, 1000.0000))
layout:setLeftMargin(0.0000)
layout:setRightMargin(0.0000)
layout:setTopMargin(0.0000)
layout:setBottomMargin(0.0000)
Image_1:addChild(scrollview)

--Create tipsstr
local tipsstr = ccui.Text:create()
tipsstr:ignoreContentAdaptWithSize(false)
tipsstr:setFontSize(40)
tipsstr:setString([[游戏报错游戏报错游戏报错游戏报错游戏报错游戏报错游戏报错游戏报错游戏报错游戏报错游戏报错游戏报错游戏报错游戏报错游戏报错]])
tipsstr:enableShadow(cc.c4b(110, 110, 110, 255), cc.size(1.0000, 1.0000), 0)
tipsstr:setLayoutComponentEnabled(true)
tipsstr:setName("tipsstr")
tipsstr:setTag(344)
tipsstr:setCascadeColorEnabled(true)
tipsstr:setCascadeOpacityEnabled(true)
tipsstr:setAnchorPoint(0.0000, 1.0000)
tipsstr:setPosition(0.0000, 1000.0000)
tipsstr:setColor(cc.c3b(0, 0, 0))
layout = ccui.LayoutComponent:bindLayoutComponent(tipsstr)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(1.0000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.2500)
layout:setSize(cc.size(1200.0000, 1000.0000))
layout:setLeftMargin(0.0000)
layout:setRightMargin(0.0000)
layout:setTopMargin(0.0000)
layout:setBottomMargin(0.0000)
scrollview:addChild(tipsstr)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

