--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene

--Create rootpanel
local rootpanel = ccui.Layout:create()
rootpanel:ignoreContentAdaptWithSize(false)
rootpanel:setBackGroundColorOpacity(102)
rootpanel:setLayoutComponentEnabled(true)
rootpanel:setName("rootpanel")
rootpanel:setTag(170)
rootpanel:setCascadeColorEnabled(true)
rootpanel:setCascadeOpacityEnabled(true)
rootpanel:setPosition(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(rootpanel)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize(cc.size(1242.0000, 2208.0000))
layout:setLeftMargin(0.0000)
layout:setRightMargin(0.0000)
layout:setTopMargin(0.0000)
layout:setBottomMargin(0.0000)
local Scene=rootpanel
Scene:setName("Scene")


--Create mainnode
local mainnode=cc.Node:create()
mainnode:setName("mainnode")
mainnode:setTag(145)
mainnode:setCascadeColorEnabled(true)
mainnode:setCascadeOpacityEnabled(true)
mainnode:setPosition(621.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(mainnode)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.0000)
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(621.0000)
layout:setRightMargin(621.0000)
layout:setTopMargin(2208.0000)
layout:setBottomMargin(0.0000)
rootpanel:addChild(mainnode)

--Create bulletscreennode
local bulletscreennode=cc.Node:create()
bulletscreennode:setName("bulletscreennode")
bulletscreennode:setTag(200)
bulletscreennode:setCascadeColorEnabled(true)
bulletscreennode:setCascadeOpacityEnabled(true)
bulletscreennode:setPosition(621.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bulletscreennode)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.0000)
layout:setHorizontalEdge(3)
layout:setLeftMargin(621.0000)
layout:setRightMargin(621.0000)
layout:setTopMargin(0.0000)
layout:setBottomMargin(0.0000)
rootpanel:addChild(bulletscreennode)

--Create popnode
local popnode=cc.Node:create()
popnode:setName("popnode")
popnode:setTag(146)
popnode:setCascadeColorEnabled(true)
popnode:setCascadeOpacityEnabled(true)
popnode:setPosition(621.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(popnode)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.0000)
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(621.0000)
layout:setRightMargin(621.0000)
layout:setTopMargin(2208.0000)
layout:setBottomMargin(0.0000)
rootpanel:addChild(popnode)

--Create lodingnode
local lodingnode=cc.Node:create()
lodingnode:setName("lodingnode")
lodingnode:setTag(81)
lodingnode:setCascadeColorEnabled(true)
lodingnode:setCascadeOpacityEnabled(true)
lodingnode:setPosition(621.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(lodingnode)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.0000)
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(621.0000)
layout:setRightMargin(621.0000)
layout:setTopMargin(2208.0000)
layout:setBottomMargin(0.0000)
rootpanel:addChild(lodingnode)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

