--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create backnode
local backnode=cc.Node:create()
backnode:setName("backnode")
backnode:setTag(263)
backnode:setCascadeColorEnabled(true)
backnode:setCascadeOpacityEnabled(true)
backnode:setPosition(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(backnode)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setLeftMargin(0.0000)
layout:setRightMargin(1242.0000)
layout:setTopMargin(2208.0000)
layout:setBottomMargin(0.0000)
Scene:addChild(backnode)

--Create backimage
local backimage = ccui.ImageView:create()
backimage:ignoreContentAdaptWithSize(false)
backimage:loadTexture("game/game_layer/common/transition/transition_bg.png",0)
backimage:setLayoutComponentEnabled(true)
backimage:setName("backimage")
backimage:setTag(503)
backimage:setCascadeColorEnabled(true)
backimage:setCascadeOpacityEnabled(true)
backimage:setPosition(621.0000, 1104.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(backimage)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(1688.0000, 2208.0000))
layout:setLeftMargin(-223.0000)
layout:setRightMargin(-1465.0000)
layout:setTopMargin(-2208.0000)
layout:setBottomMargin(0.0000)
backnode:addChild(backimage)

--Create logoimage
local logoimage = ccui.ImageView:create()
logoimage:ignoreContentAdaptWithSize(false)
logoimage:loadTexture("game/game_layer/common/transition/transition_logo.png",0)
logoimage:setLayoutComponentEnabled(true)
logoimage:setName("logoimage")
logoimage:setTag(504)
logoimage:setCascadeColorEnabled(true)
logoimage:setCascadeOpacityEnabled(true)
logoimage:setPosition(844.0000, 1104.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(logoimage)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setSize(cc.size(358.0000, 408.0000))
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(-179.0000)
layout:setRightMargin(-179.0000)
layout:setTopMargin(-204.0000)
layout:setBottomMargin(-204.0000)
backimage:addChild(logoimage)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

