--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Sprite:create()
Node:setName("Node")

--Create btn
local btn = ccui.Button:create()
btn:ignoreContentAdaptWithSize(false)
btn:loadTextureNormal("game/game_layer/ingame_poker/normal/poker_back_1.png",0)
btn:loadTexturePressed("game/game_layer/ingame_poker/normal/poker_back_1.png",0)
btn:loadTextureDisabled("game/game_layer/ingame_poker/normal/poker_back_1.png",0)
btn:setTitleFontSize(14)
btn:setTitleText("Button")
btn:setTitleColor(cc.c3b(65, 65, 70))
btn:setScale9Enabled(true)
btn:setCapInsets(cc.rect(15,11,108,164))
btn:setLayoutComponentEnabled(true)
btn:setName("btn")
btn:setTag(91)
btn:setCascadeColorEnabled(true)
btn:setCascadeOpacityEnabled(true)
btn:setPosition(0.0000, 0.0000)
btn:setOpacity(0)
if callBackProvider~=nil then
      btn:addClickEventListener(callBackProvider("cardnode.lua", btn, "OnBtnSelectCard"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btn)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(210.0000, 280.0000))
layout:setLeftMargin(-105.0000)
layout:setRightMargin(-105.0000)
layout:setTopMargin(-140.0000)
layout:setBottomMargin(-140.0000)
Node:addChild(btn)

--Create card
local card = ccui.ImageView:create()
card:ignoreContentAdaptWithSize(false)
card:loadTexture("game/game_layer/ingame_poker/normal/poker_back_1.png",0)
card:setLayoutComponentEnabled(true)
card:setName("card")
card:setTag(99)
card:setCascadeColorEnabled(true)
card:setCascadeOpacityEnabled(true)
card:setPosition(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(card)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(210.0000, 280.0000))
layout:setLeftMargin(-105.0000)
layout:setRightMargin(-105.0000)
layout:setTopMargin(-140.0000)
layout:setBottomMargin(-140.0000)
Node:addChild(card)

--Create light
local light = ccui.ImageView:create()
light:ignoreContentAdaptWithSize(false)
light:loadTexture("game/game_layer/ingame_poker/normal/poker_card_selected.png",0)
light:setLayoutComponentEnabled(true)
light:setName("light")
light:setTag(144)
light:setCascadeColorEnabled(true)
light:setCascadeOpacityEnabled(true)
light:setPosition(0.0000, -0.0001)
layout = ccui.LayoutComponent:bindLayoutComponent(light)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(210.0000, 280.0000))
layout:setLeftMargin(-105.0000)
layout:setRightMargin(-105.0000)
layout:setTopMargin(-139.9999)
layout:setBottomMargin(-140.0001)
Node:addChild(light)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

