local NNMsgId = class("NNMsgId")

NNMsgId.ID_REQ = 10000
NNMsgId.ID_ACK = 20000
NNMsgId.ID_NTF = 40000

NNMsgId.MSGID_LOGIN_GUEST = 1
NNMsgId.MSGID_LOGIN_DPQ = 2
NNMsgId.MSGID_QUICK_START = 3
NNMsgId.MSGID_JOIN_TABLE = 4
NNMsgId.MSGID_SIT_DOWN = 5
NNMsgId.MSGID_STAND_UP = 6
NNMsgId.MSGID_READY = 7
NNMsgId.MSGID_LEAVE_TABLE = 8
NNMsgId.MSGID_TABLE_EVENT = 9
NNMsgId.MSGID_BROKEN = 10
NNMsgId.MSGID_ROBOT_JOIN_TABLE = 11
NNMsgId.MSGID_ROBOT_SIT_DOWN =  12--前端没有用
NNMsgId.MSGID_LOGIN_HALL =  14--

NNMsgId.MSGID_BAI_STATUS = 101
NNMsgId.MSGID_BAI_XIAZHU = 102
NNMsgId.MSGID_BAI_BANKER_COINS_LIMIT = 103
NNMsgId.MSGID_BAI_APPLY_BANKER = 104
NNMsgId.MSGID_BAI_QUIT_BANKER = 105
NNMsgId.MSGID_BAI_CHANGE_BANKER = 106
NNMsgId.MSGID_BAI_WAIT_BANKER_LIST = 107
NNMsgId.MSGID_BAI_WIN_HISTORY = 108
NNMsgId.MSGID_BAI_BIG_WINNER = 109

NNMsgId.WEBSOCKET_ONOPEN = "webSocketOnOpen"
NNMsgId.WEBSOCKET_ONCLOSE = "webSocketOnClose"
NNMsgId.UPDATE_SEAT_COIN = "updateSeatCoin"--更新在坐玩家的金币
NNMsgId.UPDATE_SELF_COIN = "updateSelfCoin"
NNMsgId.UPDATE_BANK_COIN = "updateBankCoin"
NNMsgId.UPDATE_SELF_BET_COIN = "updateSelfBetCoin"--更新自己下注的筹码显示
NNMsgId.UPDATE_TOTAL_BET_COIN = "updateTotalBetCoin"--更新天地玄黄区域下注的筹码显示
NNMsgId.PLAY_PEEKANI_END = "playPeekAniEnd"
NNMsgId.HTTP_DPQ_LOGIN = "httpDpqLogin"--http登录成功返回
return NNMsgId