--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create rootpanel
local rootpanel = ccui.Layout:create()
rootpanel:ignoreContentAdaptWithSize(false)
rootpanel:setBackGroundColorType(1)
rootpanel:setBackGroundColor(cc.c3b(150, 200, 255))
rootpanel:setBackGroundColorOpacity(102)
rootpanel:setTouchEnabled(true);
rootpanel:setLayoutComponentEnabled(true)
rootpanel:setName("rootpanel")
rootpanel:setTag(152)
rootpanel:setCascadeColorEnabled(true)
rootpanel:setCascadeOpacityEnabled(true)
rootpanel:setAnchorPoint(0.5000, 0.5000)
rootpanel:setPosition(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(rootpanel)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize(cc.size(1242.0000, 2208.0000))
layout:setLeftMargin(-621.0000)
layout:setRightMargin(621.0000)
layout:setTopMargin(1104.0000)
layout:setBottomMargin(-1104.0000)
Scene:addChild(rootpanel)

--Create bgimg
local bgimg = ccui.ImageView:create()
bgimg:ignoreContentAdaptWithSize(false)
bgimg:loadTexture("bg1.png",0)
bgimg:setLayoutComponentEnabled(true)
bgimg:setName("bgimg")
bgimg:setTag(65)
bgimg:setCascadeColorEnabled(true)
bgimg:setCascadeOpacityEnabled(true)
bgimg:setPosition(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bgimg)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize(cc.size(1242.0000, 2208.0000))
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(-621.0000)
layout:setRightMargin(621.0000)
layout:setTopMargin(1104.0000)
layout:setBottomMargin(-1104.0000)
Scene:addChild(bgimg)

--Create btnAdd
local btnAdd = ccui.Button:create()
btnAdd:ignoreContentAdaptWithSize(false)
btnAdd:loadTextureNormal("yellow.png",0)
btnAdd:loadTexturePressed("yellow_pressed.png",0)
btnAdd:loadTextureDisabled("yellow_pressed.png",0)
btnAdd:setTitleText("加牌")
btnAdd:setTitleFontSize(36)
btnAdd:setTitleColor(cc.c3b(65, 65, 70))
btnAdd:setScale9Enabled(true)
btnAdd:setCapInsets(cc.rect(15,11,44,52))
btnAdd:setLayoutComponentEnabled(true)
btnAdd:setName("btnAdd")
btnAdd:setTag(3)
btnAdd:setCascadeColorEnabled(true)
btnAdd:setCascadeOpacityEnabled(true)
btnAdd:setAnchorPoint(0.0000, 0.5000)
btnAdd:setPosition(1000.0000, 200.0000)
if callBackProvider~=nil then
      btnAdd:addClickEventListener(callBackProvider("blackgamemainnode.lua", btnAdd, "OnAddButton"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btnAdd)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setPercentWidth(0.1192)
layout:setPercentHeight(0.0670)
layout:setSize(cc.size(148.0000, 148.0000))
layout:setLeftMargin(0.0000)
layout:setRightMargin(1094.0000)
layout:setTopMargin(89.0000)
layout:setBottomMargin(1971.0000)
bgimg:addChild(btnAdd)

--Create btnReset
local btnReset = ccui.Button:create()
btnReset:ignoreContentAdaptWithSize(false)
btnReset:loadTextureNormal("yellow.png",0)
btnReset:loadTexturePressed("yellow_pressed.png",0)
btnReset:loadTextureDisabled("yellow_pressed.png",0)
btnReset:setTitleText("重置")
btnReset:setTitleFontSize(36)
btnReset:setTitleColor(cc.c3b(65, 65, 70))
btnReset:setScale9Enabled(true)
btnReset:setCapInsets(cc.rect(15,11,44,52))
btnReset:setLayoutComponentEnabled(true)
btnReset:setName("btnReset")
btnReset:setTag(3)
btnReset:setCascadeColorEnabled(true)
btnReset:setCascadeOpacityEnabled(true)
btnReset:setAnchorPoint(0.0000, 0.5000)
btnReset:setPosition(100.0000, 200.0000)
if callBackProvider~=nil then
      btnReset:addClickEventListener(callBackProvider("blackgamemainnode.lua", btnReset, "OnResetButton"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btnReset)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setPercentWidth(0.1192)
layout:setPercentHeight(0.0670)
layout:setSize(cc.size(148.0000, 148.0000))
layout:setLeftMargin(0.0000)
layout:setRightMargin(1094.0000)
layout:setTopMargin(89.0000)
layout:setBottomMargin(1971.0000)
bgimg:addChild(btnReset)



--Create node1
local node1=cc.Node:create()
node1:setName("node1")
node1:setTag(263)
node1:setCascadeColorEnabled(true)
node1:setCascadeOpacityEnabled(true)
node1:setPosition(621.0000, 200.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(node1)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setLeftMargin(0.0000)
layout:setRightMargin(1242.0000)
layout:setTopMargin(2208.0000)
layout:setBottomMargin(0.0000)
bgimg:addChild(node1)

--Create node2
local node2=cc.Node:create()
node2:setName("node2")
node2:setTag(263)
node2:setCascadeColorEnabled(true)
node2:setCascadeOpacityEnabled(true)
node2:setPosition(200.0000, 1700.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(node2)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setLeftMargin(0.0000)
layout:setRightMargin(1242.0000)
layout:setTopMargin(2208.0000)
layout:setBottomMargin(0.0000)
bgimg:addChild(node2)

--Create node3
local node3=cc.Node:create()
node3:setName("node3")
node3:setTag(263)
node3:setCascadeColorEnabled(true)
node3:setCascadeOpacityEnabled(true)
node3:setPosition(1242-200.0000, 1700.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(node3)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setLeftMargin(0.0000)
layout:setRightMargin(1242.0000)
layout:setTopMargin(2208.0000)
layout:setBottomMargin(0.0000)
bgimg:addChild(node3)



--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

